INSERT INTO category (id, name, parent_id)
VALUES
    (99, '⭐ Nouveauté', null);

INSERT INTO shop_categories (shop_id, category_id)
VALUES
    (4, 99);

INSERT INTO shop_content (shop_id, category_id, label, price, data, stock)
VALUES
    (4, 99, 'Bonhomme de neige classique', 200, '{"components":{"1":{"Drawable":215,"Palette":0,"Texture":0}},"modelLabel":"Bonhomme de neige","colorLabel":"classique"}', 50),
    (4, 99, 'Cache-cou botanique rouge', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":0}},"modelLabel":"Cache-cou","colorLabel":"botanique rouge"}', 50),
    (4, 99, 'Cache-cou botanique noire', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":1}},"modelLabel":"Cache-cou","colorLabel":"botanique noire"}', 50),
    (4, 99, 'Cache-cou flamant rose', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":10}},"modelLabel":"Cache-cou","colorLabel":"flamant rose"}', 50),
    (4, 99, 'Cache-cou bleu clair', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":11}},"modelLabel":"Cache-cou","colorLabel":"bleu clair"}', 50),
    (4, 99, 'Cache-cou verte', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":12}},"modelLabel":"Cache-cou","colorLabel":"verte"}', 50),
    (4, 99, 'Cache-cou bleu marine', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":13}},"modelLabel":"Cache-cou","colorLabel":"bleu marine"}', 50),
    (4, 99, 'Cache-cou océan bleu', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":14}},"modelLabel":"Cache-cou","colorLabel":"océan bleu"}', 50),
    (4, 99, 'Cache-cou océan orange', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":15}},"modelLabel":"Cache-cou","colorLabel":"océan orange"}', 50),
    (4, 99, 'Cache-cou papillon bleu', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":16}},"modelLabel":"Cache-cou","colorLabel":"papillon bleu"}', 50),
    (4, 99, 'Cache-cou papillon orange', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":17}},"modelLabel":"Cache-cou","colorLabel":"papillon orange"}', 50),
    (4, 99, 'Cache-cou volcan rouge', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":18}},"modelLabel":"Cache-cou","colorLabel":"volcan rouge"}', 50),
    (4, 99, 'Cache-cou volcan rose', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":19}},"modelLabel":"Cache-cou","colorLabel":"volcan rose"}', 50),
    (4, 99, 'Cache-cou fleur bleue', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":2}},"modelLabel":"Cache-cou","colorLabel":"fleur bleue"}', 50),
    (4, 99, 'Cache-cou poisson crème', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":20}},"modelLabel":"Cache-cou","colorLabel":"poisson crème"}', 50),
    (4, 99, 'Cache-cou poisson mauve', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":21}},"modelLabel":"Cache-cou","colorLabel":"poisson mauve"}', 50),
    (4, 99, 'Cache-cou tigre crème', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":22}},"modelLabel":"Cache-cou","colorLabel":"tigre crème"}', 50),
    (4, 99, 'Cache-cou tigre rose', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":23}},"modelLabel":"Cache-cou","colorLabel":"tigre rose"}', 50),
    (4, 99, 'Cache-cou fleur mauve', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":24}},"modelLabel":"Cache-cou","colorLabel":"fleur mauve"}', 50),
    (4, 99, 'Cache-cou fleur bleu clair', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":25}},"modelLabel":"Cache-cou","colorLabel":"fleur bleu clair"}', 50),
    (4, 99, 'Cache-cou fleur noire', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":3}},"modelLabel":"Cache-cou","colorLabel":"fleur noire"}', 50),
    (4, 99, 'Cache-cou fleur bleue', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":4}},"modelLabel":"Cache-cou","colorLabel":"fleur bleue"}', 50),
    (4, 99, 'Cache-cou fleur orange', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":5}},"modelLabel":"Cache-cou","colorLabel":"fleur orange"}', 50),
    (4, 99, 'Cache-cou fleur verte', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":6}},"modelLabel":"Cache-cou","colorLabel":"fleur verte"}', 50),
    (4, 99, 'Cache-cou fleur rose', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":7}},"modelLabel":"Cache-cou","colorLabel":"fleur rose"}', 50),
    (4, 99, 'Cache-cou palmier bleu', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":8}},"modelLabel":"Cache-cou","colorLabel":"palmier bleu"}', 50),
    (4, 99, 'Cache-cou palmier jaune', 200, '{"components":{"1":{"Drawable":187,"Palette":0,"Texture":9}},"modelLabel":"Cache-cou","colorLabel":"palmier jaune"}', 50),
    (4, 99, 'Cache-cou noir', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":0}},"modelLabel":"Cache-cou","colorLabel":"noir"}', 50),
    (4, 99, 'Cache-cou gris', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":1}},"modelLabel":"Cache-cou","colorLabel":"gris"}', 50),
    (4, 99, 'Cache-cou bouche verte', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":10}},"modelLabel":"Cache-cou","colorLabel":"bouche verte"}', 50),
    (4, 99, 'Cache-cou dents de loup', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":11}},"modelLabel":"Cache-cou","colorLabel":"dents de loup"}', 50),
    (4, 99, 'Cache-cou camouflage multicolore', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":12}},"modelLabel":"Cache-cou","colorLabel":"camouflage multicolore"}', 50),
    (4, 99, 'Cache-cou crâne', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":13}},"modelLabel":"Cache-cou","colorLabel":"crâne"}', 50),
    (4, 99, 'Cache-cou trésor', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":14}},"modelLabel":"Cache-cou","colorLabel":"trésor"}', 50),
    (4, 99, 'Cache-cou crâne doré', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":15}},"modelLabel":"Cache-cou","colorLabel":"crâne doré"}', 50),
    (4, 99, 'Cache-cou camouflage', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":16}},"modelLabel":"Cache-cou","colorLabel":"camouflage"}', 50),
    (4, 99, 'Cache-cou camouflage néon vert', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":17}},"modelLabel":"Cache-cou","colorLabel":"camouflage néon vert"}', 50),
    (4, 99, 'Cache-cou camouflage néon rose', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":18}},"modelLabel":"Cache-cou","colorLabel":"camouflage néon rose"}', 50),
    (4, 99, 'Cache-cou crocodile', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":19}},"modelLabel":"Cache-cou","colorLabel":"crocodile"}', 50),
    (4, 99, 'Cache-cou blanc', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":2}},"modelLabel":"Cache-cou","colorLabel":"blanc"}', 50),
    (4, 99, 'Cache-cou serpent vert', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":20}},"modelLabel":"Cache-cou","colorLabel":"serpent vert"}', 50),
    (4, 99, 'Cache-cou serpent violet', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":21}},"modelLabel":"Cache-cou","colorLabel":"serpent violet"}', 50),
    (4, 99, 'Cache-cou rose', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":22}},"modelLabel":"Cache-cou","colorLabel":"rose"}', 50),
    (4, 99, 'Cache-cou violet', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":23}},"modelLabel":"Cache-cou","colorLabel":"violet"}', 50),
    (4, 99, 'Cache-cou orange', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":24}},"modelLabel":"Cache-cou","colorLabel":"orange"}', 50),
    (4, 99, 'Cache-cou vert foncé', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":25}},"modelLabel":"Cache-cou","colorLabel":"vert foncé"}', 50),
    (4, 99, 'Cache-cou rouge', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":3}},"modelLabel":"Cache-cou","colorLabel":"rouge"}', 50),
    (4, 99, 'Cache-cou bleu foncé', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":4}},"modelLabel":"Cache-cou","colorLabel":"bleu foncé"}', 50),
    (4, 99, 'Cache-cou smiley saignant', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":5}},"modelLabel":"Cache-cou","colorLabel":"smiley saignant"}', 50),
    (4, 99, 'Cache-cou pixel gris', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":6}},"modelLabel":"Cache-cou","colorLabel":"pixel gris"}', 50),
    (4, 99, 'Cache-cou pixel bleu', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":7}},"modelLabel":"Cache-cou","colorLabel":"pixel bleu"}', 50),
    (4, 99, 'Cache-cou vague bleue', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":8}},"modelLabel":"Cache-cou","colorLabel":"vague bleue"}', 50),
    (4, 99, 'Cache-cou USA', 200, '{"components":{"1":{"Drawable":169,"Palette":0,"Texture":9}},"modelLabel":"Cache-cou","colorLabel":"USA"}', 50),
    (4, 99, 'Cagoule de carnaval vert à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":0}},"modelLabel":"Cagoule de carnaval","colorLabel":"vert à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval bleu à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":1}},"modelLabel":"Cagoule de carnaval","colorLabel":"bleu à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval visage néon', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":10}},"modelLabel":"Cagoule de carnaval","colorLabel":"visage néon"}', 50),
    (4, 99, 'Cagoule de carnaval visage néon rouge', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":11}},"modelLabel":"Cagoule de carnaval","colorLabel":"visage néon rouge"}', 50),
    (4, 99, 'Cagoule de carnaval visage néon bleu', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":12}},"modelLabel":"Cagoule de carnaval","colorLabel":"visage néon bleu"}', 50),
    (4, 99, 'Cagoule de carnaval crâne néon', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":13}},"modelLabel":"Cagoule de carnaval","colorLabel":"crâne néon"}', 50),
    (4, 99, 'Cagoule de carnaval crâne néon vert', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":14}},"modelLabel":"Cagoule de carnaval","colorLabel":"crâne néon vert"}', 50),
    (4, 99, 'Cagoule de carnaval crâne néon rouge', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":15}},"modelLabel":"Cagoule de carnaval","colorLabel":"crâne néon rouge"}', 50),
    (4, 99, 'Cagoule de carnaval crâne néon orange', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":16}},"modelLabel":"Cagoule de carnaval","colorLabel":"crâne néon orange"}', 50),
    (4, 99, 'Cagoule de carnaval x-ray', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":17}},"modelLabel":"Cagoule de carnaval","colorLabel":"x-ray"}', 50),
    (4, 99, 'Cagoule de carnaval x-ray vert', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":18}},"modelLabel":"Cagoule de carnaval","colorLabel":"x-ray vert"}', 50),
    (4, 99, 'Cagoule de carnaval x-ray violet', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":19}},"modelLabel":"Cagoule de carnaval","colorLabel":"x-ray violet"}', 50),
    (4, 99, 'Cagoule de carnaval mauve à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":2}},"modelLabel":"Cagoule de carnaval","colorLabel":"mauve à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval orange à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":3}},"modelLabel":"Cagoule de carnaval","colorLabel":"orange à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval violet à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":4}},"modelLabel":"Cagoule de carnaval","colorLabel":"violet à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval bleu marine à fleurs', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":5}},"modelLabel":"Cagoule de carnaval","colorLabel":"bleu marine à fleurs"}', 50),
    (4, 99, 'Cagoule de carnaval néon mauve', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":6}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon mauve"}', 50),
    (4, 99, 'Cagoule de carnaval néon orange', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":7}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon orange"}', 50),
    (4, 99, 'Cagoule de carnaval néon rose', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":8}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon rose"}', 50),
    (4, 99, 'Cagoule de carnaval visage néon 2', 200, '{"components":{"1":{"Drawable":189,"Palette":0,"Texture":9}},"modelLabel":"Cagoule de carnaval","colorLabel":"visage néon 2"}', 50),
    (4, 99, 'Cagoule de carnaval alien vert', 200, '{"components":{"1":{"Drawable":134,"Palette":0,"Texture":8}},"modelLabel":"Cagoule de carnaval","colorLabel":"alien vert"}', 50),
    (4, 99, 'Cagoule de carnaval alien violet', 200, '{"components":{"1":{"Drawable":134,"Palette":0,"Texture":9}},"modelLabel":"Cagoule de carnaval","colorLabel":"alien violet"}', 50),
    (4, 99, 'Cagoule de carnaval néon moustache bleu', 200, '{"components":{"1":{"Drawable":102,"Palette":0,"Texture":0}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon moustache bleu"}', 50),
    (4, 99, 'Cagoule de carnaval néon moustache vert', 200, '{"components":{"1":{"Drawable":102,"Palette":0,"Texture":1}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon moustache vert"}', 50),
    (4, 99, 'Cagoule de carnaval néon moustache beige', 200, '{"components":{"1":{"Drawable":102,"Palette":0,"Texture":2}},"modelLabel":"Cagoule de carnaval","colorLabel":"néon moustache beige"}', 50),
    (4, 99, 'Cagoule de plongée noire', 200, '{"components":{"1":{"Drawable":122,"Palette":0,"Texture":0}},"modelLabel":"Cagoule de plongée","colorLabel":"noire"}', 50),
    (4, 99, 'Cagoule de plongée bleu foncé', 200, '{"components":{"1":{"Drawable":122,"Palette":0,"Texture":1}},"modelLabel":"Cagoule de plongée","colorLabel":"bleu foncé"}', 50),
    (4, 99, 'Cagoule de plongée bleu clair', 200, '{"components":{"1":{"Drawable":122,"Palette":0,"Texture":2}},"modelLabel":"Cagoule de plongée","colorLabel":"bleu clair"}', 50),
    (4, 99, 'Cagoule intégrale trait vert', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":0}},"modelLabel":"Cagoule intégrale","colorLabel":"trait vert"}', 50),
    (4, 99, 'Cagoule intégrale trait orange', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":1}},"modelLabel":"Cagoule intégrale","colorLabel":"trait orange"}', 50),
    (4, 99, 'Cagoule intégrale verte', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":10}},"modelLabel":"Cagoule intégrale","colorLabel":"verte"}', 50),
    (4, 99, 'Cagoule intégrale rouge', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":11}},"modelLabel":"Cagoule intégrale","colorLabel":"rouge"}', 50),
    (4, 99, 'Cagoule intégrale trait bleu', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":2}},"modelLabel":"Cagoule intégrale","colorLabel":"trait bleu"}', 50),
    (4, 99, 'Cagoule intégrale trait rose', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":3}},"modelLabel":"Cagoule intégrale","colorLabel":"trait rose"}', 50),
    (4, 99, 'Cagoule intégrale trait jaune', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":4}},"modelLabel":"Cagoule intégrale","colorLabel":"trait jaune"}', 50),
    (4, 99, 'Cagoule intégrale brun foncé', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":5}},"modelLabel":"Cagoule intégrale","colorLabel":"brun foncé"}', 50),
    (4, 99, 'Cagoule intégrale brun clair', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":6}},"modelLabel":"Cagoule intégrale","colorLabel":"brun clair"}', 50),
    (4, 99, 'Cagoule intégrale p\'tit biscuit clair', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":7}},"modelLabel":"Cagoule intégrale","colorLabel":"p\'tit biscuit clair"}', 50),
    (4, 99, 'Cagoule intégrale p\'tit biscuit foncé', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":8}},"modelLabel":"Cagoule intégrale","colorLabel":"p\'tit biscuit foncé"}', 50),
    (4, 99, 'Cagoule intégrale Père Noël', 200, '{"components":{"1":{"Drawable":123,"Palette":0,"Texture":9}},"modelLabel":"Cagoule intégrale","colorLabel":"Père Noël"}', 50),
    (4, 99, 'Cagoule intégrale rouge à pois', 200, '{"components":{"1":{"Drawable":194,"Palette":0,"Texture":0}},"modelLabel":"Cagoule intégrale","colorLabel":"rouge à pois"}', 50),
    (4, 99, 'Cagoule intégrale vert à pois', 200, '{"components":{"1":{"Drawable":194,"Palette":0,"Texture":1}},"modelLabel":"Cagoule intégrale","colorLabel":"vert à pois"}', 50),
    (4, 99, 'Cagoule tactique bigness noir', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":0}},"modelLabel":"Cagoule tactique","colorLabel":"bigness noir"}', 50),
    (4, 99, 'Cagoule tactique bigness blanc', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":1}},"modelLabel":"Cagoule tactique","colorLabel":"bigness blanc"}', 50),
    (4, 99, 'Cagoule tactique flamme verte', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":10}},"modelLabel":"Cagoule tactique","colorLabel":"flamme verte"}', 50),
    (4, 99, 'Cagoule tactique flamme orange', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":11}},"modelLabel":"Cagoule tactique","colorLabel":"flamme orange"}', 50),
    (4, 99, 'Cagoule tactique flamme rose', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":12}},"modelLabel":"Cagoule tactique","colorLabel":"flamme rose"}', 50),
    (4, 99, 'Cagoule tactique flamme violette', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":13}},"modelLabel":"Cagoule tactique","colorLabel":"flamme violette"}', 50),
    (4, 99, 'Cagoule tactique flamme rouge', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":14}},"modelLabel":"Cagoule tactique","colorLabel":"flamme rouge"}', 50),
    (4, 99, 'Cagoule tactique éclair violet', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":15}},"modelLabel":"Cagoule tactique","colorLabel":"éclair violet"}', 50),
    (4, 99, 'Cagoule tactique éclair blanc', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":16}},"modelLabel":"Cagoule tactique","colorLabel":"éclair blanc"}', 50),
    (4, 99, 'Cagoule tactique éclair vert', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":17}},"modelLabel":"Cagoule tactique","colorLabel":"éclair vert"}', 50),
    (4, 99, 'Cagoule tactique éclair orange', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":18}},"modelLabel":"Cagoule tactique","colorLabel":"éclair orange"}', 50),
    (4, 99, 'Cagoule tactique éclair violet', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":19}},"modelLabel":"Cagoule tactique","colorLabel":"éclair violet"}', 50),
    (4, 99, 'Cagoule tactique bigness violet', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":2}},"modelLabel":"Cagoule tactique","colorLabel":"bigness violet"}', 50),
    (4, 99, 'Cagoule tactique éclair rouge', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":20}},"modelLabel":"Cagoule tactique","colorLabel":"éclair rouge"}', 50),
    (4, 99, 'Cagoule tactique camouflage urbain', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":21}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage urbain"}', 50),
    (4, 99, 'Cagoule tactique camouflage aquatique', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":22}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage aquatique"}', 50),
    (4, 99, 'Cagoule tactique camouflage orange', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":23}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage orange"}', 50),
    (4, 99, 'Cagoule tactique camouflage gris', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":24}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage gris"}', 50),
    (4, 99, 'Cagoule tactique camouflage turquoise', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":25}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage turquoise"}', 50),
    (4, 99, 'Cagoule tactique blagueurs noir', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":3}},"modelLabel":"Cagoule tactique","colorLabel":"blagueurs noir"}', 50),
    (4, 99, 'Cagoule tactique blagueurs bleu', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":4}},"modelLabel":"Cagoule tactique","colorLabel":"blagueurs bleu"}', 50),
    (4, 99, 'Cagoule tactique blagueurs rouge', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":5}},"modelLabel":"Cagoule tactique","colorLabel":"blagueurs rouge"}', 50),
    (4, 99, 'Cagoule tactique blagueurs blanc', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":6}},"modelLabel":"Cagoule tactique","colorLabel":"blagueurs blanc"}', 50),
    (4, 99, 'Cagoule tactique fleur noir', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":7}},"modelLabel":"Cagoule tactique","colorLabel":"fleur noir"}', 50),
    (4, 99, 'Cagoule tactique fleur turquoise', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":8}},"modelLabel":"Cagoule tactique","colorLabel":"fleur turquoise"}', 50),
    (4, 99, 'Cagoule tactique fleur rose', 200, '{"components":{"1":{"Drawable":211,"Palette":0,"Texture":9}},"modelLabel":"Cagoule tactique","colorLabel":"fleur rose"}', 50),
    (4, 99, 'Cagoule tactique multicolore', 200, '{"components":{"1":{"Drawable":212,"Palette":0,"Texture":0}},"modelLabel":"Cagoule tactique","colorLabel":"multicolore"}', 50),
    (4, 99, 'Cagoule tactique camouflage gris', 200, '{"components":{"1":{"Drawable":212,"Palette":0,"Texture":1}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage gris"}', 50),
    (4, 99, 'Cagoule tactique camouflage yeti', 200, '{"components":{"1":{"Drawable":212,"Palette":0,"Texture":2}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage yeti"}', 50),
    (4, 99, 'Cagoule tactique camouflage rose', 200, '{"components":{"1":{"Drawable":212,"Palette":0,"Texture":3}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage rose"}', 50),
    (4, 99, 'Cagoule tactique écriture rouge', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":0}},"modelLabel":"Cagoule tactique","colorLabel":"écriture rouge"}', 50),
    (4, 99, 'Cagoule tactique branche noire', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":1}},"modelLabel":"Cagoule tactique","colorLabel":"branche noire"}', 50),
    (4, 99, 'Cagoule tactique USA', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":10}},"modelLabel":"Cagoule tactique","colorLabel":"USA"}', 50),
    (4, 99, 'Cagoule tactique crâne noir', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":11}},"modelLabel":"Cagoule tactique","colorLabel":"crâne noir"}', 50),
    (4, 99, 'Cagoule tactique crâne blanc', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":12}},"modelLabel":"Cagoule tactique","colorLabel":"crâne blanc"}', 50),
    (4, 99, 'Cagoule tactique verte', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":13}},"modelLabel":"Cagoule tactique","colorLabel":"verte"}', 50),
    (4, 99, 'Cagoule tactique orange', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":14}},"modelLabel":"Cagoule tactique","colorLabel":"orange"}', 50),
    (4, 99, 'Cagoule tactique violette', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":15}},"modelLabel":"Cagoule tactique","colorLabel":"violette"}', 50),
    (4, 99, 'Cagoule tactique rose', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":16}},"modelLabel":"Cagoule tactique","colorLabel":"rose"}', 50),
    (4, 99, 'Cagoule tactique San Andreas', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":17}},"modelLabel":"Cagoule tactique","colorLabel":"San Andreas"}', 50),
    (4, 99, 'Cagoule tactique étoiles noires', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":18}},"modelLabel":"Cagoule tactique","colorLabel":"étoiles noires"}', 50),
    (4, 99, 'Cagoule tactique rouge et noire', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":19}},"modelLabel":"Cagoule tactique","colorLabel":"rouge et noire"}', 50),
    (4, 99, 'Cagoule tactique Xero citron vert', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":2}},"modelLabel":"Cagoule tactique","colorLabel":"Xero citron vert"}', 50),
    (4, 99, 'Cagoule tactique abstrait', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":20}},"modelLabel":"Cagoule tactique","colorLabel":"abstrait"}', 50),
    (4, 99, 'Cagoule tactique camo bigness', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":21}},"modelLabel":"Cagoule tactique","colorLabel":"camo bigness"}', 50),
    (4, 99, 'Cagoule tactique Xero tropical', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":3}},"modelLabel":"Cagoule tactique","colorLabel":"Xero tropical"}', 50),
    (4, 99, 'Cagoule tactique trait rouge', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":4}},"modelLabel":"Cagoule tactique","colorLabel":"trait rouge"}', 50),
    (4, 99, 'Cagoule tactique bigness kaki', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":5}},"modelLabel":"Cagoule tactique","colorLabel":"bigness kaki"}', 50),
    (4, 99, 'Cagoule tactique orange', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":6}},"modelLabel":"Cagoule tactique","colorLabel":"orange"}', 50),
    (4, 99, 'Cagoule tactique multicolore', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":7}},"modelLabel":"Cagoule tactique","colorLabel":"multicolore"}', 50),
    (4, 99, 'Cagoule tactique bigness bleu', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":8}},"modelLabel":"Cagoule tactique","colorLabel":"bigness bleu"}', 50),
    (4, 99, 'Cagoule tactique jaune', 200, '{"components":{"1":{"Drawable":113,"Palette":0,"Texture":9}},"modelLabel":"Cagoule tactique","colorLabel":"jaune"}', 50),
    (4, 99, 'Cagoule tactique complète noire', 200, '{"components":{"1":{"Drawable":35,"Palette":0,"Texture":0}},"modelLabel":"Cagoule tactique","colorLabel":"complète noire"}', 50),
    (4, 99, 'Cagoule tactique noire', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":0}},"modelLabel":"Cagoule tactique","colorLabel":"noire"}', 50),
    (4, 99, 'Cagoule tactique gris clair', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":1}},"modelLabel":"Cagoule tactique","colorLabel":"gris clair"}', 50),
    (4, 99, 'Cagoule tactique crâne', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":10}},"modelLabel":"Cagoule tactique","colorLabel":"crâne"}', 50),
    (4, 99, 'Cagoule tactique blanche', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":2}},"modelLabel":"Cagoule tactique","colorLabel":"blanche"}', 50),
    (4, 99, 'Cagoule tactique verte', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":3}},"modelLabel":"Cagoule tactique","colorLabel":"verte"}', 50),
    (4, 99, 'Cagoule tactique kaki', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":4}},"modelLabel":"Cagoule tactique","colorLabel":"kaki"}', 50),
    (4, 99, 'Cagoule tactique gris foncé', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":5}},"modelLabel":"Cagoule tactique","colorLabel":"gris foncé"}', 50),
    (4, 99, 'Cagoule tactique camouflage vert', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":6}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage vert"}', 50),
    (4, 99, 'Cagoule tactique camouflage gris', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":7}},"modelLabel":"Cagoule tactique","colorLabel":"camouflage gris"}', 50),
    (4, 99, 'Cagoule tactique bleue', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":8}},"modelLabel":"Cagoule tactique","colorLabel":"bleue"}', 50),
    (4, 99, 'Cagoule tactique jaune', 200, '{"components":{"1":{"Drawable":52,"Palette":0,"Texture":9}},"modelLabel":"Cagoule tactique","colorLabel":"jaune"}', 50),
    (4, 99, 'Crâne orange', 200, '{"components":{"1":{"Drawable":108,"Palette":0,"Texture":22}},"modelLabel":"Crâne","colorLabel":"orange"}', 50),
    (4, 99, 'Cyborg vert', 200, '{"components":{"1":{"Drawable":110,"Palette":0,"Texture":22}},"modelLabel":"Cyborg","colorLabel":"vert"}', 50),
    (4, 99, 'Cyborg orange', 200, '{"components":{"1":{"Drawable":110,"Palette":0,"Texture":23}},"modelLabel":"Cyborg","colorLabel":"orange"}', 50),
    (4, 99, 'Cyborg violet', 200, '{"components":{"1":{"Drawable":110,"Palette":0,"Texture":24}},"modelLabel":"Cyborg","colorLabel":"violet"}', 50),
    (4, 99, 'Cyborg rose', 200, '{"components":{"1":{"Drawable":110,"Palette":0,"Texture":25}},"modelLabel":"Cyborg","colorLabel":"rose"}', 50),
    (4, 99, 'Gooch classique', 200, '{"components":{"1":{"Drawable":213,"Palette":0,"Texture":0}},"modelLabel":"Gooch","colorLabel":"classique"}', 50),
    (4, 99, 'Juge en bois', 200, '{"components":{"1":{"Drawable":210,"Palette":0,"Texture":0}},"modelLabel":"Juge","colorLabel":"en bois"}', 50),
    (4, 99, 'Lapin blanc', 200, '{"components":{"1":{"Drawable":209,"Palette":0,"Texture":0}},"modelLabel":"Lapin","colorLabel":"blanc"}', 50),
    (4, 99, 'Lapin cosmique', 200, '{"components":{"1":{"Drawable":209,"Palette":0,"Texture":1}},"modelLabel":"Lapin","colorLabel":"cosmique"}', 50),
    (4, 99, 'Lapin blanc et rouge', 200, '{"components":{"1":{"Drawable":209,"Palette":0,"Texture":2}},"modelLabel":"Lapin","colorLabel":"blanc et rouge"}', 50),
    (4, 99, 'Mandibule vert', 200, '{"components":{"1":{"Drawable":112,"Palette":0,"Texture":22}},"modelLabel":"Mandibule","colorLabel":"vert"}', 50),
    (4, 99, 'Mandibule orange', 200, '{"components":{"1":{"Drawable":112,"Palette":0,"Texture":23}},"modelLabel":"Mandibule","colorLabel":"orange"}', 50),
    (4, 99, 'Mandibule violet', 200, '{"components":{"1":{"Drawable":112,"Palette":0,"Texture":24}},"modelLabel":"Mandibule","colorLabel":"violet"}', 50),
    (4, 99, 'Mandibule rose', 200, '{"components":{"1":{"Drawable":112,"Palette":0,"Texture":25}},"modelLabel":"Mandibule","colorLabel":"rose"}', 50),
    (4, 99, 'Masque super-héros', 200, '{"components":{"1":{"Drawable":148,"Palette":0,"Texture":0}},"modelLabel":"Masque","colorLabel":"super-héros"}', 50),
    (4, 99, 'Masque sapin vert clair', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":0}},"modelLabel":"Masque sapin","colorLabel":"vert clair"}', 50),
    (4, 99, 'Masque sapin vert foncé', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":1}},"modelLabel":"Masque sapin","colorLabel":"vert foncé"}', 50),
    (4, 99, 'Masque sapin noir', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":2}},"modelLabel":"Masque sapin","colorLabel":"noir"}', 50),
    (4, 99, 'Masque sapin blanc', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":3}},"modelLabel":"Masque sapin","colorLabel":"blanc"}', 50),
    (4, 99, 'Masque sapin rouge', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":4}},"modelLabel":"Masque sapin","colorLabel":"rouge"}', 50),
    (4, 99, 'Masque sapin violet', 200, '{"components":{"1":{"Drawable":77,"Palette":0,"Texture":5}},"modelLabel":"Masque sapin","colorLabel":"violet"}', 50),
    (4, 99, 'Miteuse pixel', 200, '{"components":{"1":{"Drawable":119,"Palette":0,"Texture":21}},"modelLabel":"Miteuse","colorLabel":"pixel"}', 50),
    (4, 99, 'Miteuse camouflage', 200, '{"components":{"1":{"Drawable":119,"Palette":0,"Texture":22}},"modelLabel":"Miteuse","colorLabel":"camouflage"}', 50),
    (4, 99, 'Miteuse blanche', 200, '{"components":{"1":{"Drawable":119,"Palette":0,"Texture":23}},"modelLabel":"Miteuse","colorLabel":"blanche"}', 50),
    (4, 99, 'Miteuse néon', 200, '{"components":{"1":{"Drawable":119,"Palette":0,"Texture":24}},"modelLabel":"Miteuse","colorLabel":"néon"}', 50),
    (4, 99, 'Rennes brun clair', 200, '{"components":{"1":{"Drawable":214,"Palette":0,"Texture":0}},"modelLabel":"Rennes","colorLabel":"brun clair"}', 50),
    (4, 99, 'Rennes brun foncé', 200, '{"components":{"1":{"Drawable":214,"Palette":0,"Texture":1}},"modelLabel":"Rennes","colorLabel":"brun foncé"}', 50),
    (4, 99, 'Rhinocéros jaune', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":0}},"modelLabel":"Rhinocéros","colorLabel":"jaune"}', 50),
    (4, 99, 'Rhinocéros vert', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":1}},"modelLabel":"Rhinocéros","colorLabel":"vert"}', 50),
    (4, 99, 'Rhinocéros noir', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":10}},"modelLabel":"Rhinocéros","colorLabel":"noir"}', 50),
    (4, 99, 'Rhinocéros orange', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":2}},"modelLabel":"Rhinocéros","colorLabel":"orange"}', 50),
    (4, 99, 'Rhinocéros bleu', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":3}},"modelLabel":"Rhinocéros","colorLabel":"bleu"}', 50),
    (4, 99, 'Rhinocéros rose', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":4}},"modelLabel":"Rhinocéros","colorLabel":"rose"}', 50),
    (4, 99, 'Rhinocéros rouge', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":5}},"modelLabel":"Rhinocéros","colorLabel":"rouge"}', 50),
    (4, 99, 'Rhinocéros bleu marine', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":6}},"modelLabel":"Rhinocéros","colorLabel":"bleu marine"}', 50),
    (4, 99, 'Rhinocéros gris foncé', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":7}},"modelLabel":"Rhinocéros","colorLabel":"gris foncé"}', 50),
    (4, 99, 'Rhinocéros brun', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":8}},"modelLabel":"Rhinocéros","colorLabel":"brun"}', 50),
    (4, 99, 'Rhinocéros blanc', 200, '{"components":{"1":{"Drawable":91,"Palette":0,"Texture":9}},"modelLabel":"Rhinocéros","colorLabel":"blanc"}', 50),
    (4, 99, 'Voyeur brun', 200, '{"components":{"1":{"Drawable":170,"Palette":0,"Texture":0}},"modelLabel":"Voyeur","colorLabel":"brun"}', 50),
    (4, 99, 'Yéti de Noël blanc', 200, '{"components":{"1":{"Drawable":83,"Palette":0,"Texture":3}},"modelLabel":"Yéti de Noël","colorLabel":"blanc"}', 50),
    (4, 99, 'Bandana pixel', 200, '{"components":{"1":{"Drawable":230,"Palette":0,"Texture":0}},"modelLabel":"Bandana","colorLabel":"pixel"}', 50),
    (4, 99, 'Bandana crème', 200, '{"components":{"1":{"Drawable":230,"Palette":0,"Texture":1}},"modelLabel":"Bandana","colorLabel":"crème"}', 50),
    (4, 99, 'Bandana camo urbain', 200, '{"components":{"1":{"Drawable":230,"Palette":0,"Texture":2}},"modelLabel":"Bandana","colorLabel":"camo urbain"}', 50),
    (4, 99, 'Bandana gris', 200, '{"components":{"1":{"Drawable":230,"Palette":0,"Texture":3}},"modelLabel":"Bandana","colorLabel":"gris"}', 50),
    (4, 99, 'Bandana blanc', 200, '{"components":{"1":{"Drawable":234,"Palette":0,"Texture":0}},"modelLabel":"Bandana","colorLabel":"blanc"}', 50),
    (4, 99, 'Bandana starpz', 200, '{"components":{"1":{"Drawable":234,"Palette":0,"Texture":1}},"modelLabel":"Bandana","colorLabel":"starpz"}', 50),
    (4, 99, 'Bandana bleu clair', 200, '{"components":{"1":{"Drawable":234,"Palette":0,"Texture":2}},"modelLabel":"Bandana","colorLabel":"bleu clair"}', 50),
    (4, 99, 'Bandana bleu foncé', 200, '{"components":{"1":{"Drawable":234,"Palette":0,"Texture":3}},"modelLabel":"Bandana","colorLabel":"bleu foncé"}', 50),
    (4, 99, 'Bandana carnaval', 200, '{"components":{"1":{"Drawable":235,"Palette":0,"Texture":0}},"modelLabel":"Bandana","colorLabel":"carnaval"}', 50),
    (4, 99, 'Cagoule vert et rouge', 200, '{"components":{"1":{"Drawable":236,"Palette":0,"Texture":0}},"modelLabel":"Cagoule intégrale","colorLabel":"vert et rouge"}', 50),
    (4, 99, 'Cagoule grille noire', 200, '{"components":{"1":{"Drawable":233,"Palette":0,"Texture":0}},"modelLabel":"Forces spéciales","colorLabel":"grille noire"}', 50),
    (4, 99, 'Cagoule pixel noire', 200, '{"components":{"1":{"Drawable":233,"Palette":0,"Texture":1}},"modelLabel":"Forces spéciales","colorLabel":"pixel noire"}', 50),
    (4, 99, 'Cagoule strie noire', 200, '{"components":{"1":{"Drawable":233,"Palette":0,"Texture":2}},"modelLabel":"Forces spéciales","colorLabel":"strie noire"}', 50),
    (4, 99, 'Masque de dragon bois', 200, '{"components":{"1":{"Drawable":229,"Palette":0,"Texture":0}},"modelLabel":"Masque de dragon","colorLabel":"bois"}', 50),
    (4, 99, 'Masque de dragon coloré', 200, '{"components":{"1":{"Drawable":229,"Palette":0,"Texture":1}},"modelLabel":"Masque de dragon","colorLabel":"coloré"}', 50),
    (4, 99, 'Masque de dragon royal', 200, '{"components":{"1":{"Drawable":229,"Palette":0,"Texture":2}},"modelLabel":"Masque de dragon","colorLabel":"royal"}', 50),
    (4, 99, 'Masque de dragon minuit', 200, '{"components":{"1":{"Drawable":229,"Palette":0,"Texture":3}},"modelLabel":"Masque de dragon","colorLabel":"minuit"}', 50),
    (4, 99, 'Masque diable vintage rouge', 200, '{"components":{"1":{"Drawable":216,"Palette":0,"Texture":0}},"modelLabel":"Masque diable vintage","colorLabel":"rouge"}', 50),
    (4, 99, 'Masque diable vintage vert', 200, '{"components":{"1":{"Drawable":216,"Palette":0,"Texture":2}},"modelLabel":"Masque diable vintage","colorLabel":"vert"}', 50),
    (4, 99, 'Masque diable vintage bronze', 200, '{"components":{"1":{"Drawable":216,"Palette":0,"Texture":1}},"modelLabel":"Masque diable vintage","colorLabel":"bronze"}', 50),
    (4, 99, 'Masque loup-garou vintage orange', 200, '{"components":{"1":{"Drawable":217,"Palette":0,"Texture":0}},"modelLabel":"Masque loup-garou vintage","colorLabel":"orange"}', 50),
    (4, 99, 'Masque loup-garou vintage bleu', 200, '{"components":{"1":{"Drawable":217,"Palette":0,"Texture":1}},"modelLabel":"Masque loup-garou vintage","colorLabel":"bleu"}', 50),
    (4, 99, 'Masque loup-garou vintage brun', 200, '{"components":{"1":{"Drawable":217,"Palette":0,"Texture":2}},"modelLabel":"Masque loup-garou vintage","colorLabel":"brun"}', 50),
    (4, 99, 'Masque de sorcière vintage vert', 200, '{"components":{"1":{"Drawable":218,"Palette":0,"Texture":0}},"modelLabel":"Masque de sorcière vintage","colorLabel":"vert"}', 50),
    (4, 99, 'Masque de sorcière vintage jaune', 200, '{"components":{"1":{"Drawable":218,"Palette":0,"Texture":1}},"modelLabel":"Masque de sorcière vintage","colorLabel":"jaune"}', 50),
    (4, 99, 'Masque de sorcière vintage orange', 200, '{"components":{"1":{"Drawable":218,"Palette":0,"Texture":2}},"modelLabel":"Masque de sorcière vintage","colorLabel":"orange"}', 50),
    (4, 99, 'Masque de zombie vintage vert', 200, '{"components":{"1":{"Drawable":219,"Palette":0,"Texture":0}},"modelLabel":"Masque de zombie vintage","colorLabel":"vert"}', 50),
    (4, 99, 'Masque de zombie vintage brun', 200, '{"components":{"1":{"Drawable":219,"Palette":0,"Texture":1}},"modelLabel":"Masque de zombie vintage","colorLabel":"brun"}', 50),
    (4, 99, 'Masque de zombie vintage bleu sarcelle', 200, '{"components":{"1":{"Drawable":219,"Palette":0,"Texture":2}},"modelLabel":"Masque de zombie vintage","colorLabel":"bleu sarcelle"}', 50),
    (4, 99, 'Masque de crâne vintage vert', 200, '{"components":{"1":{"Drawable":220,"Palette":0,"Texture":0}},"modelLabel":"Masque de crâne vintage","colorLabel":"vert"}', 50),
    (4, 99, 'Masque de crâne vintage blanc', 200, '{"components":{"1":{"Drawable":220,"Palette":0,"Texture":1}},"modelLabel":"Masque de crâne vintage","colorLabel":"blanc"}', 50),
    (4, 99, 'Masque de crâne vintage brun', 200, '{"components":{"1":{"Drawable":220,"Palette":0,"Texture":2}},"modelLabel":"Masque de crâne vintage","colorLabel":"brun"}', 50),
    (4, 99, 'Masque de dindon', 200, '{"components":{"1":{"Drawable":223,"Palette":0,"Texture":0}},"modelLabel":"Masque de dindon","colorLabel":"classique"}', 50),
    (4, 99, 'Masque Calacas royal', 200, '{"components":{"1":{"Drawable":225,"Palette":0,"Texture":0}},"modelLabel":"Masque Calacas","colorLabel":"royal"}', 50),
    (4, 99, 'Masque Calacas floral', 200, '{"components":{"1":{"Drawable":225,"Palette":0,"Texture":3}},"modelLabel":"Masque Calacas","colorLabel":"floral"}', 50),
    (4, 99, 'Masque Calacas maritime', 200, '{"components":{"1":{"Drawable":225,"Palette":0,"Texture":1}},"modelLabel":"Masque Calacas","colorLabel":"maritime"}', 50),
    (4, 99, 'Masque Calacas romance', 200, '{"components":{"1":{"Drawable":225,"Palette":0,"Texture":2}},"modelLabel":"Masque Calacas","colorLabel":"romance"}', 50)
--  Bottom Dollar Bounties
--  (4, 99, 'Masque crâne rouge', 200, '{"components":{"1":{"Drawable":241,"Palette":0,"Texture":0}},"modelLabel":"Masque crâne","colorLabel":"rouge"}', 50),
--  (4, 99, 'Masque crâne vert', 200, '{"components":{"1":{"Drawable":241,"Palette":0,"Texture":1}},"modelLabel":"Masque crâne","colorLabel":"vert"}', 50),
--  (4, 99, 'Masque crâne orange', 200, '{"components":{"1":{"Drawable":241,"Palette":0,"Texture":2}},"modelLabel":"Masque crâne","colorLabel":"orange"}', 50),
--  (4, 99, 'Masque crâne à capuche gris', 200, '{"components":{"1":{"Drawable":240,"Palette":0,"Texture":0}},"modelLabel":"Masque crâne à capuche","colorLabel":"gris"}', 50),
--  (4, 99, 'Masque crâne à capuche rouge', 200, '{"components":{"1":{"Drawable":240,"Palette":0,"Texture":1}},"modelLabel":"Masque crâne à capuche","colorLabel":"rouge"}', 50),
--  (4, 99, 'Masque crâne à capuche bleu', 200, '{"components":{"1":{"Drawable":240,"Palette":0,"Texture":2}},"modelLabel":"Masque crâne à capuche","colorLabel":"bleu"}', 50),
--  (4, 99, 'Masque de chèvre noir', 200, '{"components":{"1":{"Drawable":238,"Palette":0,"Texture":0}},"modelLabel":"Masque de chèvre","colorLabel":"noir"}', 50),
--  (4, 99, 'Masque de chèvre rouge', 200, '{"components":{"1":{"Drawable":238,"Palette":0,"Texture":1}},"modelLabel":"Masque de chèvre","colorLabel":"rouge"}', 50),
--  (4, 99, 'Masque de chèvre bronzé', 200, '{"components":{"1":{"Drawable":238,"Palette":0,"Texture":2}},"modelLabel":"Masque de chèvre","colorLabel":"bronzé"}', 50),
--  (4, 99, 'Masque chat effrayant noir', 200, '{"components":{"1":{"Drawable":239,"Palette":0,"Texture":0}},"modelLabel":"Masque chat effrayant","colorLabel":"noir"}', 50),
--  (4, 99, 'Masque chat effrayant gris', 200, '{"components":{"1":{"Drawable":239,"Palette":0,"Texture":1}},"modelLabel":"Masque chat effrayant","colorLabel":"gris"}', 50),
--  (4, 99, 'Masque chat effrayant brun', 200, '{"components":{"1":{"Drawable":239,"Palette":0,"Texture":2}},"modelLabel":"Masque chat effrayant","colorLabel":"brun"}', 50),
--  (4, 99, 'Singe fumeur de cigare', 200, '{"components":{"1":{"Drawable":237,"Palette":0,"Texture":0}},"modelLabel":"Singe fumeur","colorLabel":"cigare"}', 50),
--  (4, 99, 'Masque de poulet', 200, '{"components":{"1":{"Drawable":242,"Palette":0,"Texture":0}},"modelLabel":"Masque de poulet","colorLabel":"classique"}', 50)